### TEST/GET WEBSITE

GET http://localhost:3001/test

### GET/ DATA

GET http://localhost:3001/data

###POST


POST http://localhost:3001/new-data
Content-Type: application/json

{
  "name": "arun"
}

### DELETE

DELETE http://localhost:3001/delete


### GET/ DATA

GET http://localhost:3001/data


